NAME: 'MEDCLIP.FINETUNE.RN50.vqa_rad.50epoch'
OUTPUT_DIR: './output/medclip_finetune/RN50/vqa_rad'
RESULTS_DIR: './output/medclip_finetune/RN50/vqa_rad/results'
CPU_MODE: False
INPUT_SIZE: (250, 250)

DATASET:
  DATASET: 'ROCO'
  DATA_TYPE: 'jpg'
  TRAIN_JSON: "/workspace/data/VQA-RAD/vqa_rad_train_pubmedclip.jsonl"
  VALID_JSON: "/workspace/data/VQA-RAD/vqa_rad_test_pubmedclip.jsonl"
  DATA_DIR: '/workspace/data/VQA-RAD/images'

LOSS:
  LOSS_TYPE: 'CrossEntropy'

TRAIN:
  MAX_SEQ_LENGTH: 77 
  BATCH_SIZE: 64 
  N_EPOCH: 50 
  NUM_WORKERS: 2 
  RESUME: False 
  INPUT_SNAPSHOT: "" 
  VISION_ENCODER: "RN50"
  PRETRAINED_MODEL_PATH: "/workspace/model/PubMedCLIP/PubMedCLIP_RN50.pth"
  LOAD_PRETRAINED: True
  FREEZE_VISION_ENCODER: False
  FREEZE_TEXT_ENCODER: False
  OPTIMIZER:
    TYPE: 'ADAM'
    BASE_LR: 5e-6 
    WEIGHT_DECAY: 5e-4 
    EPS: 1e-6
